# Используем легковесный образ Python
FROM python:3.11-slim

# Устанавливаем системные зависимости 
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем и устанавливаем зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем исходный код приложения
COPY ./app ./app

# Открываем порт для FastAPI 
EXPOSE 8001

# По умолчанию запускаем FastAPI. 
# Для запуска в режиме Celery-воркера эта команда переопределяется в docker-compose или при docker run
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001"]