# Generated by Django 6.0.4 on 2026-05-05 07:05

import character_creation.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConceptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('ai_response', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя персонажа')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=character_creation.models.character_directory_path)),
                ('race', models.CharField(max_length=50, verbose_name='Раса')),
                ('char_class', models.CharField(max_length=50, verbose_name='Класс')),
                ('subclass', models.CharField(blank=True, max_length=50, verbose_name='Подкласс')),
                ('level', models.PositiveIntegerField(default=1)),
                ('strength', models.IntegerField(default=8)),
                ('dexterity', models.IntegerField(default=8)),
                ('constitution', models.IntegerField(default=8)),
                ('intelligence', models.IntegerField(default=8)),
                ('wisdom', models.IntegerField(default=8)),
                ('charisma', models.IntegerField(default=8)),
                ('armor_class', models.PositiveIntegerField(default=10, verbose_name='Класс доспеха')),
                ('speed', models.PositiveIntegerField(default=30, verbose_name='Скорость')),
                ('initiative', models.IntegerField(default=0, verbose_name='Инициатива')),
                ('max_hp', models.PositiveIntegerField(default=10, verbose_name='Макс. ХП')),
                ('hit_die', models.CharField(default='1d8', max_length=10, verbose_name='Кость хитов')),
                ('alignment', models.CharField(blank=True, max_length=50, verbose_name='Мировоззрение')),
                ('size', models.CharField(default='Medium', max_length=20, verbose_name='Размер')),
                ('prof_athletics', models.BooleanField(default=False)),
                ('prof_acrobatics', models.BooleanField(default=False)),
                ('prof_sleight_of_hand', models.BooleanField(default=False)),
                ('prof_stealth', models.BooleanField(default=False)),
                ('prof_arcana', models.BooleanField(default=False)),
                ('prof_history', models.BooleanField(default=False)),
                ('prof_investigation', models.BooleanField(default=False)),
                ('prof_nature', models.BooleanField(default=False)),
                ('prof_religion', models.BooleanField(default=False)),
                ('prof_animal_handling', models.BooleanField(default=False)),
                ('prof_insight', models.BooleanField(default=False)),
                ('prof_medicine', models.BooleanField(default=False)),
                ('prof_perception', models.BooleanField(default=False)),
                ('prof_survival', models.BooleanField(default=False)),
                ('prof_deception', models.BooleanField(default=False)),
                ('prof_intimidation', models.BooleanField(default=False)),
                ('prof_performance', models.BooleanField(default=False)),
                ('prof_persuasion', models.BooleanField(default=False)),
                ('concept_origin', models.TextField(blank=True, verbose_name='Исходный концепт')),
                ('backstory', models.TextField(blank=True, verbose_name='Предыстория')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
