# Generated by Django 6.0.4 on 2026-05-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_creation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='background',
            field=models.CharField(blank=True, max_length=100, verbose_name='Предыстория'),
        ),
        migrations.AddField(
            model_name='character',
            name='current_hp',
            field=models.IntegerField(default=10, verbose_name='Текущие ХП'),
        ),
        migrations.AddField(
            model_name='character',
            name='equipment',
            field=models.TextField(blank=True, verbose_name='Снаряжение'),
        ),
        migrations.AddField(
            model_name='character',
            name='experience_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Опыт'),
        ),
        migrations.AddField(
            model_name='character',
            name='features',
            field=models.TextField(blank=True, verbose_name='Умения и особенности'),
        ),
        migrations.AddField(
            model_name='character',
            name='gold',
            field=models.PositiveIntegerField(default=0, verbose_name='Золото'),
        ),
        migrations.AddField(
            model_name='character',
            name='is_draft',
            field=models.BooleanField(default=True, verbose_name='Черновик'),
        ),
        migrations.AddField(
            model_name='character',
            name='languages',
            field=models.TextField(blank=True, verbose_name='Языки'),
        ),
        migrations.AddField(
            model_name='character',
            name='prof_cha_save',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='prof_con_save',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='prof_dex_save',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='prof_int_save',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='prof_str_save',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='prof_wis_save',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='spells',
            field=models.JSONField(blank=True, default=list, verbose_name='Список заклинаний'),
        ),
        migrations.AddField(
            model_name='character',
            name='tool_proficiencies',
            field=models.TextField(blank=True, verbose_name='Инструменты'),
        ),
    ]
