# Generated by Django 6.0.4 on 2026-05-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_creation', '0002_character_background_character_current_hp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('rus_name', models.CharField(max_length=50, unique=True)),
                ('hit_die', models.CharField(default='1d8', max_length=5)),
                ('saving_throws', models.CharField(max_length=100)),
                ('skill_slots', models.PositiveIntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('rus_name', models.CharField(max_length=50, unique=True)),
                ('speed', models.PositiveIntegerField(default=30)),
                ('size', models.CharField(default='Medium', max_length=20)),
                ('features', models.TextField(help_text='Расовые особенности')),
            ],
        ),
    ]
