# Generated by Django 6.0.4 on 2026-05-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_creation', '0003_charclass_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='cha_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='race',
            name='con_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='race',
            name='dex_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='race',
            name='int_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='race',
            name='str_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='race',
            name='wis_bonus',
            field=models.IntegerField(default=0),
        ),
    ]
