# Generated by Django 6.0.4 on 2026-05-06 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_creation', '0004_race_cha_bonus_race_con_bonus_race_dex_bonus_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconceptlog',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character_creation.character'),
        ),
        migrations.AddField(
            model_name='aiconceptlog',
            name='concept',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aiconceptlog',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiconceptlog',
            name='status',
            field=models.CharField(choices=[('pending', 'В обработке'), ('success', 'Успешно'), ('error', 'Ошибка')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='aiconceptlog',
            name='ai_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aiconceptlog',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aiconceptlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
